# Generated by Django 2.2.6 on 2019-10-28 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('voting_start', models.DateField()),
                ('voting_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='contestant_images')),
                ('vote', models.IntegerField(blank=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('adm_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Contest')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Contestant')),
            ],
        ),
        migrations.AddField(
            model_name='contestant',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Student'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Position'),
        ),
        migrations.AddField(
            model_name='contest',
            name='open_positions',
            field=models.ManyToManyField(to='Core.Position'),
        ),
    ]
