# Generated by Django 2.2.6 on 2019-10-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='registration_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='registration_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contestant_images'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='vote',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
