# Generated by Django 2.2.6 on 2019-10-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20191028_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='vote',
        ),
    ]
