# Generated by Django 2.2.6 on 2019-11-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_remove_contestant_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
