# Generated by Django 2.2.6 on 2019-11-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_contestant_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('voting ongoing', 'voting ongoing'), ('registration ongoing', 'registration ongoing'), ('registration ended', 'registration ended'), ('relesed', 'relesed')], default='active', max_length=50),
        ),
    ]
